### ISSUE TITLE
CouchDBClient Constructor error

### ISSUE THREAD

**Issue by BrigJ** [legodude17/couchdb-client#1]
Hi you have an error in the CouchDBClient Constructor that means it always connects to localhost on port 5984, regardless of what parameters the user passes in.

```
var CouchDBClient = function (options) {
    this.options = {};
    Object.assign(this.options, options,  {
        host: '127.0.0.1',
        port: '5984'
    });
    this.place = 'http://' + this.options.host + ':' + this.options.port;
};
```

At the moment this always overwrites any passed in options with the default options, if you change the Object.assign line to 

```
Object.assign(this.options,  {
        host: '127.0.0.1',
        port: '5984'
    }, options);
```

Then that will work and will make 127.0.0.1 the default setting, but will allow it to be overridden with  a user defined host and port.

**Comment by legodude17** [comment]
Closing as I just merged your pull.
